- README.md
tslint needs to resolve the `"extends":`, so `dtslint` should be installed locally.
> Remove README section about using globally

- tslint.json
This rule is causing some problems on DefinitelyTyped and we'll have to fix it later.
> Disable no-object-literal-type-assertion

- dtslint.json
This should prevent lint warnings from popping up unannounced each time a new tslint minor version is released.
> Use "tslint:recommended" instead of "tslint:latest"

- package.json
This isn't normally imported directly because we use `installs` for that instead, but since this determines the version of tslint installed, and it doesn't just happen at development time, it makes more sense to have this here.
> Move "tslint" from devDependencies to dependencies

- src/lint.ts
- src/rules/expectRule.ts
This will be fixed by palantir/tslint#2773, so this is just a workaround until then.
> Set `resolvedModules` on every source file so tslint thinks it is type checked

- src/installer.ts
- src/lint.ts
- src/rules/expectRule.ts
A problem was happening when two dtslint installs existed. One was in types-publisher, the other was in DefinitelyTyped. We would install typescript versions in the types-publisher one, but the tslint rulesDirectory would resolve to the dtslint install in DefinitelyTyped, which would then `require()` from its own `typescriptInstalls` and fail.
> Change `expect` options to use the path to TypeScript instead of the version

- package.json
- src/lint.ts
- src/rules/expectRule.ts
This rule was taking O(n^2) time based on the number of input files, because it created a new Program every time it was run. Added memoization so that it only creates 1 additional program.
> In `expect`, memoize `createProgram`

- src/rules/noPaddingRule.ts
It's rare, but if there was a parse problem, an `(` could be the last token, or a `)` could be the first token. We should avoid crashing in that case.
> Check array bounds in noPaddingRule

- src/index.ts
Currently when running `npm run lint @bla/foo` in https://github.com/DefinitelyTyped/DefinitelyTyped it errors with:
```
➜  DefinitelyTyped git:(add-@storybook__react) ✗ npm run lint @storybook/react
> definitely-typed@0.0.1 lint /Users/joscha/Development/DefinitelyTyped
> dtslint types "@storybook/react"
ENOENT: no such file or directory, open '/Users/joscha/Development/DefinitelyTyped/types/@storybook/react/index.d.ts'
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint" "@storybook/react"
npm ERR! node v7.5.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! definitely-typed@0.0.1 lint: `dtslint types "@storybook/react"`
npm ERR! Exit status 1
```
for scoped packages.
references https://github.com/Microsoft/dts-gen/pull/63, …
> Allow `dtslint types @bla/foo`

- src/index.ts
`execScript` always returned void, but we were accessing the value as if it were a string. (Microsoft/TypeScript#17892)
Also updated `usage()` to use `console.error` since that seems more appropriate.
> Fix error reporting for `--noLint`

- docs/no-self-import.md
- dt.json
- src/rules/noSelfImportRule.ts
Prevents unnecessary global imports from the current package.
> Add "no-self-import" rule

- docs/no-declare-current-package.md
- dt.json
- src/rules/noDeclareCurrentPackageRule.ts
- src/rules/noSelfImportRule.ts
- src/util.ts
Should prevent writing `declare module "foo/bar"` where a file `foo/bar.d.ts` would have worked.
> Add 'no-declare-current-package' rule

- src/checks.ts
- src/index.ts
"Unknown compiler option" error will be ignored to retain compatibility with typescript < 2.6.
> Require strictFunctionTypes in tsconfig.json

- docs/no-outside-dependencies.md
- dt.json
- src/rules/noOutsideDependenciesRule.ts
Prevents packages from depending on things in `DefinitelyTyped/node_modules`.
> Add `no-outside-dependencies` lint rule

- src/lint.ts
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21446#issuecomment-344035032
> Error on 'ts-ignore' or 'tslint:disable' comments

- README.md
`rulesDirectory` causes `error: unknown option '--rulesDirectory'`. [cli documentation](https://palantir.github.io/tslint/usage/cli/) only mentions `rules-dir`.
> tslint cli argument name was changed

- docs/no-single-element-tuple-type.md
- src/rules/noSingleElementTupleTypeRule.ts
- test/no-single-element-tuple-type/test.ts.lint
- test/no-single-element-tuple-type/tslint.json
Inspired by DefinitelyTyped/DefinitelyTyped#21387
> Add 'no-single-element-tuple-type' rule

- docs/dt-header.md
Assuming that the ` at the end of the "good example" of the "Definitions by" shouldn't be there.
> Removing ` from good example in dt-header

- docs/no-const-enum.md
- dtslint.json
- src/rules/noConstEnumRule.ts
- test/no-const-enum/test.ts.lint
- test/no-const-enum/tslint.json
Fixes #102
Especially looking for review on `docs/no-const-enum.md` since users will be wondering what the alternative is.
> Add 'no-const-enum' rule

- package-lock.json
- package.json
- src/checks.ts
- src/index.ts
- src/installer.ts
- src/lint.ts
- src/util.ts
The owner of fs-promise deprecated it and recommends using fs-extra.
I ran build/lint/test against Node.js versions `6.10.2`, `8.11.2`, and `10.2.1`.
> Switch module fs-promise to fs-extra

- README.md
If you just C&P'd like I did, you get:
```sh
Error: Expected `"strictNullChecks": true` or `"strictNullChecks": false`.
at Object.<anonymous> (/Users/orta/dev/projects/oss/js/tipsi-stripe/node_modules/dtslint/bin/checks.js:97:23)
at Generator.next (<anonymous>)
at fulfilled (/Users/orta/dev/projects/oss/js/tipsi-stripe/node_modules/dtslint/bin/checks.js:4:58)
```
This sets a reasonable default.
> Update README.md's example tsconfig

- src/checks.ts
- src/util.ts
Currently using dtslint in the root of a monorepo requires calling the cli for each package which requires that each package holds a tsconfig which is reasonable enough but ignores the `extends` property in those files. 
This pull requests use the typescript api to parse the tsconfig similar to how `tsc` would do it. The code is largely inspired by https://github.com/palantir/tslint/blob/788f64c9b101ef719290a62f7d67ca5162d821e4/src/linter.ts#L58-L83. Typescript currently does not include definitons for `parseConfigFileWithSystem` (but is exported) which is used by `tsc` https://github.com/Microsoft/TypeScript/blob/92205cf3e4ec06abfaa7e139bcc3dc2090a5294f/src/tsc/tsc.ts#L146
After writing this and fully realizing from where I took this code I went ahead and just used `tslint` while using …
> Respect "extends" in tsconfig.json

- src/util.ts
#130 broke tests because `ts.parseJsonConfigFileContent` processes the options and changes them.
It looks like the user who submitted that PR @eps1lon was attempting to use some dtslint rules in a regular TypeScript repo, so a better solution would be to move those rules upstream or publish them independently.
> Revert #130: load tsconfig with just readjson, not ts.parseJsonConfigFileContent

- docs/dt-header.md
- package-lock.json
- src/checks.ts
- src/index.ts
- src/installer.ts
- src/lint.ts
- src/rules/dtHeaderRule.ts
- src/rules/expectRule.ts
- src/util.ts
- test/dt-header/wrong/types/foo/notIndex.d.ts.lint
Users on DT will be able to add `ts3.1` directories. dtslint must:
* Warn on Suspicious directories like `ts3.0` (didn't support typesVersions) `ts3.2` (not out yet).
* Ensure `package.json` is set appropriately.
* For each TypeScript version, test in the appropriate directory.
> Support typesVersions (`ts3.1` directories)

- dtslint.json
Since angle bracket type assertions were replaced by the `as` syntax, it's probably a good idea to use this instead. See also the [rationale on the lint page](https://palantir.github.io/tslint/rules/no-angle-bracket-type-assertion/).
> Enable no-angle-bracket-type-assertion

- src/index.ts
- src/lint.ts
The main lint run should not lint files in typesVersions subdirectories. That's taken care of in a subsequent call to `lint`.
> skip files in typesVersions subdirectories

- src/lint.ts
TypeScriptVersion.all's last member is the unreleased version of Typescript, which is not on npm. When the lint code requests a version range, always return a range without the unreleased version.
> Do not test unreleased version of TS

- src/index.ts
- src/installer.ts
At the moment if you supply `--onlyTestTsNext` it still installs **all** the typescript packages when it only needs to install the `next` one. 
This fixes this.
Can we merge this in ASAP please 👍
> if `onlyTestTsNext` is set to true only install the "next" typescript

- src/index.ts
Only the biggest projects should require the use of typesVersion. Everybody else should be able to require 3.2 or above without keeping old versions around.
> Remove typesVersions requirement

- package-lock.json
- src/rules/expectRule.ts
- test/expect/expectType.ts.lint
This lets `// $ExpectType ReadonlyArray<T>` match `readonly T[]` for arbitrarily nested instances of `readonly T[]`.
> Let '$ExpectType ReadonlyArray<T>' match 'readonly T[]'

- src/.vscode/launch.json
- src/checks.ts
Definitely Typed already has 3 existing packages that have 'download' in the name. Allow these names.
cc @SimonSchick
> Exempt existing packages from 'download' forbidden word

- src/installer.ts
Very minor update, for example:
Before:
```
Installing to .../dtslint/typescript-installs/2.0...
Installed!
Installing to .../dtslint/typescript-installs/2.1...
Installed!
Installing to .../dtslint/typescript-installs/2.2...
Installed!
```
After:
```
Installing to .../dtslint/typescript-installs/2.0...
Installed!
Installing to .../dtslint/typescript-installs/2.1...
Installed!
Installing to .../dtslint/typescript-installs/2.2...
Installed!
```
Thought that the readability may improve a bit.
Cheers for the library
> Update installer log output

- src/lint.ts
With `dtslint` setup on private types repo one thing caused my a lot of frustration before I looked up the source code - tslint extends does not allow array value, even only with one element.
It's non-intuitive and for me personally `tslint-config-prettier` is a must :)
```json5
// tslint.json
{
// This is fine
"extends": "dtslint/dtslint.json",
}
```
```json5
{
// This is not, and it probably should
"extends": ["dtslint/dtslint.json"],
}
```
```json5
{
// This is also not, and probably should be allowed for non-DefinitelyTyped users
"extends": ["dtslint/dtslint.json", "tslint-config-prettier"],
}
```
Well, why not enable it? 6 lines of code, works for me :smirk:  : 
It may be prudent to lock this feature for `dt = true`, just in case. Let me know I can update it.
> Respect extends in tslint.json

- src/index.ts
- src/installer.ts
- src/lint.ts
eg
```
$ dtslint --localTs ~/ts/built/local types jsqrcode
```
Like --onlyTestTsNext, this only tests with one version of Typescript.
> add --localTs flag: run with locally built TS

- src/rules/strictExportDeclareModifiersRule.ts
- test/strict-export-declare-modifiers/testModuleTs.ts.lint
It's only redundant in d.ts files
Fixes #209
> Allow `export declare` in test (.ts) files

- src/rules/dtHeaderRule.ts
- src/rules/npmNamingRule.ts
- src/util.ts
It's not necessary to keep those URLs up-to-date, and there are about 150 of them.
> Skip npm-naming rule on old versions

- src/rules/expectRule.ts
Write the data to a file with the same name in `~/.dts/perf/some-package-name.json`. Consumers can then read the file and display information from there. Note that tslint rules are not expected to write files, so perhaps there's a better way to log this information.
types-publisher and dtslint-runner need to be updated to display the data. Here's a simple script that runs on the output of dtslint-runner:
```js
const fs = require('fs');
const stats = require('stats-lite');
/** @type {Array<[string, number, number]>} */
let big = []
let types = []
for (const filename of fs.readdirSync('~/.dts/perf/', { encoding: "utf8" })) {
/** @type {{ [s: string]: { typeCount: number, memory: number } }} */
const x = JSON.parse(fs.readFileSync('~/.dts/perf/' + filename, { encoding: 'utf8' }))
for (const …
```
> Log simple performance data from expect rule

- src/index.ts
This PR calls `resolve` on the argument supplied to the `localTs` command-line option - so that a path relative to the current directory can be passed.
ATM, it's necessary to pass an absolute path, as the dtslint implementation passes the supplied path to `require` in files within two different directories - so it's not possible to pass a relative path that works with both locations.
The need to pass an absolute path necessitated [some shenanigans in RxJS](https://github.com/ReactiveX/rxjs/pull/4712), where we use dtslint to test type declarations:
> The command must be passed an absolute path to the directory that contains typescript.js as said path is passed to require in two files within the dtslint implementation that reside in different directories - so each has a different relative …
> Resolve localTs path

- package-lock.json
- package.json
- src/checks.ts
- src/index.ts
- src/rules/npmNamingRule.ts
1. Update to dts-critic 1.2, which no longer requires project urls to include the homepage url specified on npm.
2. Check for banned words for all packages, not just those complex enough to have a package.json. The location of the check was wrong.
> Fix banned words check and update dts-critic

- src/rules/expectRule.ts
I didn't add a test because tslint doesn't support baselines with newlines in them. It works locally, though.
We noticed this when trying to figure out why a clever fix to Ember tests didn't work -- turns out that it failed on 2.8 but succeeded on all subsequent versions.
> Show TS version in ExpectType error

- README.md
The CLI accepts these options (`localTs` and `expectOnly`) but they're not documented anywhere. I have to look through the issues to realize they exist.
`--localTs` - https://github.com/microsoft/dtslint/issues/231#issuecomment-515769378
`--expectOnly` - https://github.com/microsoft/dtslint/issues/208#issuecomment-467977621
I think it'd be very helpful if this information could be found on the readme as well.
> Add documentation about localTs and expectOnly option

- src/installer.ts
Currently, if the TS version already cached our `npm t` output looks like this:
> Remove long series of empty lines in tool output

- README.md
I was reading through the readme and saw what appeared to be a missing word (not 100% sure).
I'm guessing there's supposed to be a `to` in that sentence.
> Fix typo in readme (#251)

- package-lock.json
- package.json
- src/index.ts
- src/installer.ts
- src/lint.ts
Follow on from https://github.com/microsoft/definitelytyped-header-parser/pull/28
> Drop support for 2.0  2.7

- src/index.ts
Sorry @sandersn 🙈 
Fixes a mistake in #265 
I couldn’t figure out how to test this with the existing test setup. I guess if it doesn’t get recognized as a TS Version line, it just gets treated as a normal comment and doesn’t error, so you can’t really test it as a lint rule itself.
> Fix regex typo for Minimum TypeScript Version

- package.json
Node 10 is actively supported so it would be nice not to break compatibility.
https://nodejs.org/en/about/releases/
> Support Node 10

- dt.json
- package-lock.json
- package.json
- src/lint.ts
- src/rules/npmNamingRule.ts
- src/updateConfig.ts
- tsconfig.json
This PR creates a script that runs TSLint for DT packages, taking as configuration `dt.json` and ignoring the existing `tslint.json` for the package. The output is a new `tslint.json` for the packages, that only adds exemptions for rules that actually produced lint failures.
> Tslint updater

- package-lock.json
- src/rules/npmNamingRule.ts
- src/suggestions.ts
The ideia is that npm-naming (and future rules) may have some lint failures that we'd like to treat as suggestions instead of errors. So when the rule detects such a suggestion, it can now call `addSuggestions` instead of the usual TSLint `addFailure`. The ultimate goal is that when dtslint is run in CI builds, we can have the suggestions in the CI logs that can later be parsed and used for PR comments in DT.
Since there is no built-in suggestions mechanism within TSLint, the suggestion mechanism works by writing the suggestions to files in a specific directory (`~/.dts/suggestions`), one file per package linted, and then types-publisher will aggregate those files and log all the suggestions to console.
> Add support for lint suggestions

- src/checks.ts
This disallows setting `"strict": false` in **DefinitelyTyped** packages, as there’s no package that has `strict` set to `false`, only 3 that have it set to `true`.
I’m opening this as a new PR, because <https://github.com/microsoft/dtslint/pull/275> depends on all **DefinitelyTyped** packages having `"noImplicitAny": true`, which will require fixing the remaining 49 packages that won’t yet be fixed by <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42682>.
---
I’ve also disallowed overriding `"strict": true` with `"noImplicitAny"`, `"noImplicitThis"`, `"strictNullChecks"` or `"strictFunctionTypes"`, as no **DefinitelyTyped** package does this either.
> feat: Disallow `"strict": false`

- package-lock.json
- src/index.ts
- src/installer.ts
- src/lint.ts
- src/util.ts
Except when installing from npm. definitelytyped-header-parser has it right, but dtslint previously went through hoops to add "next" so that it could install `typescript@next` from npm. This PR reduces the scope of that addition to just `installer.ts`. Everywhere else just treats the next version as a normal version number.
> Use TypeScriptVersion.latest instead of "next"

- src/lint.ts
I noticed an issue when running dtslint, I would get errors due to excess files appearing from `typesVersions` directories (like `ts3.9`). Turns out this was due to the fact I was running the command on Windows and our check for `isTypesVersionPath` wasn't normalizing the path before performing a string comparison.
Fixes #160
> Fix issue with path comparison for typesVersions on Windows file systems

- package-lock.json
- src/index.ts
- src/util.ts
Follow-up to https://github.com/microsoft/types-publisher/pull/723.
This was causing [CI on DT](https://travis-ci.org/github/DefinitelyTyped/DefinitelyTyped/builds/667674430#L544) to fail for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43179.
I couldn't figure out how to write a test to exercise this code-path. If it’s easy to point out, I’d gladly add test coverage.
> Support parallel minor versions

- dtslint.json
Not sure why they fail yet -- I'll investigate on Friday.
Some others may fail too, but these two are the worst offenders.
> Disable failing custom lint rules

- dt.json
- dtslint.json
- package-lock.json
- package.json
1. Update to dts-critic and @definitelytyped/definitions-parser that use peerDeps for typescript.
2. Specify dts-critic@latest instead of a specific version.
3. Re-enable the disabled lint rules.
> Update and re-enable tslint rules

- package.json
Fixes <https://github.com/microsoft/dtslint/issues/281>
> chore(deps): Move `typescript` to `peerDependencies`

- src/rules/noRedundantJsdoc2Rule.ts
In DT, if a .d.ts includes `@deprecated` in their types then as of 4.0 we pass back a `JSDocDeprecatedTag` but that hasn't been recognized yet in dtslint.
Kinda fixes https://github.com/microsoft/dtslint/issues/299 but with a hack
In lieu of https://github.com/microsoft/dtslint/pull/285 and eventually a subsequent PR to 4.0 - I _think_ this would fix CI on DT to detect the new JSDoc tag.
Should probably unblock https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46238
> Adds a rough approximation of deprecated support

- package.json
- src/index.ts
- src/lint.ts
1. Update @definitelytyped dependencies to @next
2. Simplify+invert runTests
Next steps:
1. I'll wait until I get all my DT changes to pass, then I'll publish @definitelytyped.
2. Then I'll update this PR to @definitelytyped/*@latest, merge and publish a new version of dtslint.
3. Then I'll create PRs for the DT changes. I created the first one at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46960/files for testing purposes.
> Flip typesVersions

- src/lint.ts
Should make the next step very obvious if you hit https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24788
> Adds a message telling you to npm install when there's missing deps

- package-lock.json
- src/lint.ts
- src/rules/noRedundantJsdoc2Rule.ts
- test/no-redundant-jsdoc2/test.ts.lint
1. Update package-lock, including dts-critic' npm@7 fixes
2. Don't forbid ts-ignore or tslint:disable inside node_modules
3. Allow or disallow a bunch of new JSDoc tags.
> Update jsdoc tags + housekeeping + ts-ignore fix

- docs/no-unnecessary-generics.md
Copy [this advice](https://github.com/DefinitelyTyped/DefinitelyTyped#user-content-common-mistakes:~:text=If%20a%20type%20parameter%20does%20not,just%20have%20a%20disguised%20type%20assertion) from the DefinitelyTyped common mistakes, since it explains not only what this rule matches, but why, and this doc is where authors are sent when it fails.
> Copy advice from the DT common mistakes

- dtslint.json
It is going to turn into redundant-undefined soon, but in the meantime I need to turn off the rule so that I can switch DT from complying with no-redundant-undefined to complying with redundant-undefined.
> Disable no-redundant-undefined rule

- src/index.ts
- src/util.ts
- test/dt-header/correct/types/foo/v0.75/index.d.ts.lint
- test/dt-header/correct/types/foo/v1/index.d.ts.lint
Does not allow arbitrary minor versions, only 0.*
Matches microsoft/types-publisher#723
Fixes #333
> Allow pre-1.0 /v* subdirectories.

- src/rules/noSingleDeclareModuleRule.ts
- test/no-single-declare-module/wildcard.d.ts.lint
Hello, I'm having trouble publishing a new DefinitelyTyped module (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55011) because a linting rule unintentionally forbids single [wildcard module declarations](https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations).
Here is a fix (with tests) that solves my issue.
Have a nice day!
See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55011/checks?check_run_id=3288906960#step:6:94
> fix(no-single-declare-module): allow single wildcard module declaration

- src/rules/noDeclareCurrentPackageRule.ts
- src/rules/noSingleDeclareModuleRule.ts
- test/no-single-declare-module/wrong.d.ts.lint
The term now is just 'module'. I improved the wording while I was here.
> Remove 'external module' wording from rules

- README.md
Does it make sense to synchronize the `tsconfig.json` prescribed in the README with the dts-gen template? https://github.com/microsoft/dts-gen/blob/af84657554e01fcfa81b210a43efd8236f476fd4/lib/definitely-typed.ts#L100-L110
This PR adds `"types": []` and `"forceConsistentCasingInFileNames: true` to the README. Similar to #77 and #122 although the current example probably only actually errors on DefinitelyTyped, not if you're running dtslint on some other library: https://github.com/microsoft/dtslint/blob/33eb773bb8213bfdc0d938d309270e5fb5173a66/src/checks.ts#L61-L71
Still, I maybe ran into this [here](https://github.com/mdx-js/mdx/pull/1622#:~:text=the%20issue%20i%20encountered%20was%20dtslint%20implicitly%20including%20and%20checking%20every%20node_modules%2F%40types%20declaration%3A) -- …
> Sync README tsconfig.json with dts-gen template

- README.md
I ran into this issue [here](https://github.com/mdx-js/mdx/pull/1622/checks?check_run_id=3451812571#step:5:373):
```
$ lerna run test-types
lerna notice cli v3.22.1
lerna info ci enabled
lerna info Executing command in 8 packages: "yarn run test-types"
lerna ERR! yarn run test-types exited 1 in '@mdx-js/react'
lerna ERR! yarn run test-types stdout:
$ dtslint types
Installing to /home/runner/.dts/typescript-installs/3.8...
Installed!
Installing to /home/runner/.dts/typescript-installs/4.0...
Installed!
Installing to /home/runner/.dts/typescript-installs/4.2...
Installed!
Installing to /home/runner/.dts/typescript-installs/4.3...
Installed!
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test-types stderr:
Error: Cannot find module …
```
> Add concurrency explanation -> FAQ
