- package.json
- src/index.ts
- src/installer.ts
- src/lint.ts
- src/rules/definitelytyped-header-parser.ts
- src/rules/dtHeaderRule.ts
Could be a while before that's published.
> Inline definitelytyped-header-parser dependency

- src/index.ts
- src/rules/noRedundantModifiersRule.ts
- src/rules/noVarRule.ts
* Don't recommend `export global`
* Allow var declaration inside `declare global`
> Fixes related to "declare global"

- dtslint.json
Companion to DefinitelyTyped/DefinitelyTyped#16029
> Lint for namespaces in tests

- src/rules/definitelytyped-header-parser.ts
Fixes #31. I will mark this as prerelease in types-publisher.
> Support TypeScript 2.3

- dtslint.json
Somehow #35 didn't take effect. Doing it again.
> Use "tslint:recommended" instead of "tslint:latest"

- package.json
- src/rules/exportJustNamespaceRule.ts
- src/rules/noSingleDeclareModuleRule.ts
> Drop tsutils dependency, typescript now provides type predicates

- dt.json
- dtslint.json
- package-lock.json
Already fixed most of these errors on DT, but will run tests again as more errors may have popped up in the interim.
> Apply stricter linting

- src/index.ts
Also removed documentation of "tsNext" which was removed.
> Remove "clean" command -- "installAll" should be sufficient

- package-lock.json
- package.json
- src/rules/definitelytyped-header-parser.ts
- src/types/github-username-regex.d.ts
- tsconfig.json
Fixes DefinitelyTyped/DefinitelyTyped#19373
> Allow github usernames beginning/ending in `-`

- src/rules/expectRule.ts
This was giving us problems if there was a template literal anywhere in the file -- that broke the scanner and it no longer yielded any comments.
> 'expect': Don't use TypeScript scanner to parse error comments, just use a regexp

- docs/no-any-union.md
- docs/no-dead-reference.md
- dtslint.json
- src/rules/noAnyUnionRule.ts
- test/no-any-union/test.d.ts.lint
- test/no-any-union/tslint.json
Lint-rule version of DefinitelyTyped/DefinitelyTyped#19445
> Add `no-any-union` rule

- src/checks.ts
- src/rules/noAnyUnionRule.ts
Companion to DefinitelyTyped/DefinitelyTyped#19483
> Require `"private": true` for DefinitelyTyped package.json files

- src/rules/noUnnecessaryGenericsRule.ts
- test/no-unnecessary-generics/test.ts.lint
> no-unnecessary-generics: Count use in constraint; and error on never-used type parameters

- src/index.ts
- src/installer.ts
Won't be necessary if we do DefinitelyTyped/DefinitelyTyped#21009
> Remove `--noLint`

- src/rules/expectRule.ts
> Fix bug: ts2.0 does not have `isVariableStatement`

- src/checks.ts
Companion to Microsoft/types-publisher#412
> Allow "license" in 'package.json'

- src/index.ts
> Error on package that has a DefinitelyTyped header but is not in DefinitelyTyped

- src/index.ts
Should fix https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27171#issuecomment-403959596
> Delay calling 'installAll' until listener is set up

- dtslint.json
> Disable file-name-casing lint rule

- src/lint.ts
> Allow tslint:disable:rulename

- src/checks.ts
- src/index.ts
Fixes Microsoft/types-publisher#500
> Always use forward slash when asserting tsconfig content

- package-lock.json
- src/rules/expectRule.ts
- test/expect/expectError.ts.lint
- test/expect/expectType.ts.lint
> Print version on lint error

- src/lint.ts
- src/rules/expectRule.ts
Fixes #153
The problem was that we were relying on `expectRule` to give us compile errors in external dependencies. Now that we have typesVersions, the set of source files included is different between different TS versions. Previously we were relying on `program.getSourceFile(ctx.sourceFile.fileName)!;` to always succeed because `ctx.sourceFile` came from the linter's program, but it always won't work anymore since the linter's program and expectRule's program may come from different TS versions.
The fix is to test external dependencies for errors separately before doing anything with tslint. We will now never lint external dependencies. (Previously we were only linting with expectRule anyway.)
> Fix testing of external dependencies

- dtslint.json
- package-lock.json
- package.json
Also get rid of tabs in dtslint.json.
> Update tslint to 5.12

- src/installer.ts
Fixes https://github.com/Microsoft/dtslint/issues/169.
> Install typescripts to homedir so any dtslint can share them

- src/index.ts
This rule should never be disabled in new packages!
> Disable dts-critic when dt-header is disabled in tslint.json

- src/rules/dtHeaderRule.ts
- test/dt-header/wrong/types/default-author-name/index.d.ts.lint
People keep on missing this one.
> Forbid default author name "My Self".

- package-lock.json
- package.json
Maybe I'm missing something but I don't see why it was added in
https://github.com/microsoft/dtslint/commit/3c57139d7e2afa4600846a00123843e85e42083e
> Remove unused 'request' dependency

- docs/npm-naming.md
- package-lock.json
- package.json
- src/rules/npmNamingRule.ts
- test/npm-naming/code/tslint.json
- test/npm-naming/code/types/dts-critic/index.d.ts
- test/npm-naming/code/types/dts-critic/index.d.ts.lint
- test/npm-naming/name/tslint.json
- test/npm-naming/name/types/parseltongue/index.d.ts
- test/npm-naming/name/types/parseltongue/index.d.ts.lint
Updates to npm naming rule to be compatible with new dts-critic checks.
> Update npm naming

- src/index.ts
This part of the code doesn’t have test coverage, but I validated it locally with @definitelytyped/dtslint-runner by `npm link`ing it.
Also avoids installing all TypeScript versions under `--listen` mode when `--onlyTestTsNext` is passed.
> Ensure TypeScript is installed before starting

- dt.json
It is also broken on typescript@next
> Disable no-redundant-jsdoc-2

- package.json
- src/rules/noRedundantJsdoc2Rule.ts
- test/no-redundant-jsdoc/declarationFile.d.ts
- test/no-redundant-jsdoc/tslint.json
- test/no-relative-import-in-test/testFile.ts
Allows deprecated tags anywhere - should unblock https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46238
> Allow JSDoc deprecated anywhere
